name: Update Snake

on:
  schedule:
    - cron: '0 0 * * *'   # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:        # Cho phép chạy thủ công

jobs:
  update-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Leo-now
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark

      - name: Check for generated snake SVG
        run: |
          echo "Checking if the snake file exists..."
          ls -alh assets/
          if [ ! -f "assets/github-snake.svg" ]; then
            echo "SVG file not found!"
            exit 1
          fi

      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "Update contribution snake"
          push: true
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
